---
language: go

go:
- 1.6

install: go get github.com/revel/cmd/revel
script: revel test github.com/nucklehead/sikse-pou-nou-tout-sit

deploy:
  provider: heroku
  api_key: $HEROKU_KEY
  app: sikse-pou-nou-tout

